### ISSUE TITLE
review maths

### ISSUE THREAD

**Issue by perrygeo** [mapbox/rio-color#10]
We need a quick review of the formulas. Everything looks good, outputs are almost exactly what imagemagick gives us but just to be safe...

* [x] add [detailed docstrings](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#docstring-standard) explaining the parameters, their domains, references to literature, etc
* [x] write some validation logic in the functions to catch parameters that are outside the expected domains (e.g. arrays not scaled 0 to 1)
* [x] review unit tests, `test_operations.py` and see if the current tests make sense and if there are additional edge cases we should be testing for.

/cc @virginiayung

**Comment by virginiayung** [comment]
### Completed:
Docstrings, validation logic, unit tests (including edge cases)
- [x] sigmoidal
- [x] gamma
- [x] simple_atmo
- [x] parse operations

### To Do:
Validation Logic and unit tests for after Cython implementation of saturation. See https://github.com/mapbox/rio-color/pull/21 and https://github.com/mapbox/rio-color/pull/22
- [ ] rgb2lch
- [ ] lch2rgb
- [ ] saturation


cc @perrygeo @celoyd

**Comment by perrygeo** [comment]
@virginiayung thanks! 

The saturation stuff *currently* is very simple and relies on scikit-image to do all the difficult colorspace math. But in #22, I've rewritten the saturation function in Cython to eek some more performance out of it. There's a lot more going on since I had to do the colorspace conversions manually - the new functions are called

* [`_lch_to_rgb`](https://github.com/mapbox/rio-color/pull/22/files#diff-95c76491b778a6c285115b03e0976920R155)
* [`_rgb_to_lch`](https://github.com/mapbox/rio-color/pull/22/files#diff-95c76491b778a6c285115b03e0976920R197)
* [`saturate_rgb`](https://github.com/mapbox/rio-color/pull/22/files#diff-95c76491b778a6c285115b03e0976920R73)

**Comment by perrygeo** [comment]
I think with @virginiayung @ericfischer and my eyes on it, and after some real-world application and testing, we can call the saturation/colorspace math 👌
