### ISSUE TITLE
Easy conversion from rio atmos to rio color

### ISSUE THREAD

**Issue by perrygeo** [mapbox/rio-color#26]
`rio atmos` is a nice high-level tool for getting imagery looking good without much fiddling.

The downside is that systems using `rio color` won't we able to directly use those color formulas. The `rio atmos` forumulas can be broken down into `rio color` operations. We should provide an easy way to do that, maybe:

```
rio atmos --as-color
```

Other options?

**Comment by perrygeo** [comment]
Note that while all `rio atmos` formulas can be expressed as `rio color` operations, the reverse is not the case.

**Comment by celoyd** [comment]
:+1: `rio atmos --as-color` printing the `rio color` equivalence seems exactly right to me.
