### ISSUE TITLE
Manylinux wheels

### ISSUE THREAD

**Issue by perrygeo** [mapbox/rio-color#44]
As part of the release process, we might consider building manylinux wheels to allow easy installation on linux without a build toolchain. I *think* that, because `colorspace.so` does not link to any external shared objects, that this should be fairly lightweight and rely on the libgdal that is linked to Rasterio.

@sgillies do we want to include this in [frs-wheel-builds](https://github.com/sgillies/frs-wheel-builds)?

cc @vincentsarago

**Comment by sgillies** [comment]
@perrygeo I don't get it, but will check: colorspace.so is a new extension module?

**Comment by perrygeo** [comment]
Nothing new, `rio color.colorspace` has been implemented in Cython [since April](https://github.com/mapbox/rio-color/commit/418fcd34a8e83efedf2a389a454da27e64e12848) but installation on linux could be simplified by using wheels.

**Comment by sgillies** [comment]
I don't want to add to the frs wheel builder because it's super hacky, but it's the pragmatic thing to do for 1.0.

**Comment by sgillies** [comment]
Done: https://github.com/sgillies/frs-wheel-builds/blob/master/CHANGES#L4-L7.
