### ISSUE TITLE
Use ufuncs for speeed

### ISSUE THREAD

**Issue by perrygeo** [mapbox/rio-color#48]
Investigate the use of ufuncs, numpy's [Universal Functions](https://docs.scipy.org/doc/numpy/reference/ufuncs.html) for highly optimized maths.

`parse_operations` (or a variant of) could return ufuncs instead of standard python functions.

cc @sgillies

**Comment by sgillies** [comment]
@perrygeo I just want to remind myself to check that the rio-color functions weren't looping over pixels. I don't see any sign of that, so we can close this, or turn it into a more general speedups and optimization ticket.
