### ISSUE TITLE
Unable to install rio-color using pip in Windows 10

### ISSUE THREAD

**Issue by rosswin** [mapbox/rio-color#58]
Hey,

I am having trouble installing rio-color using the command 'pip install rio-color'.  I appreciate any support you can provide.

Here is my setup:
Windows 10 64-bit
pip 10.0.1
conda 4.5.8
python 3.6

When I run 'conda list' I see that I have:
twisted 17.5.0
automat 0.7.0

I have installed the following 'Included' tools from Visual Studio Build Tools 2017 15.7.5:
Visual C++ Build Tools core features
VC++ 2017 version 15.7 v14.14 latest v141 tools
Visual C++ 2017 Redistributable Update

I have also installed the following 'Optional' tools from Visual Studio Build Tools 2017 15.7.5:
Windows 10 SDK (10.0.17134.0)
Testing tools core features - Build Tools
C++/CLI support
Windows 10 SDK (10.0.15063.0) for Desktop C++ 
VC++ 2015.3 v14.00 (v140) toolset for desktop
Visual C++ compilers and libraries for ARM

Here is the error I am getting:

Collecting rio-color
  Using cached https://files.pythonhosted.org/packages/66/41/8f4203efe15d2d679f59095611089b7a2f64cf1944d88954ef4e3819065c/rio-color-0.4.1.tar.gz
Requirement already satisfied: click in c:\users\ross.winans\appdata\local\continuum\anaconda3\envs\osgeo-36\lib\site-packages (from rio-color) (6.7)
Requirement already satisfied: rasterio>=1.0a11 in c:\users\ross.winans\appdata\local\continuum\anaconda3\envs\osgeo-36\lib\site-packages (from rio-color) (1.0.0)
Requirement already satisfied: rio-mucho in c:\users\ross.winans\appdata\local\continuum\anaconda3\envs\osgeo-36\lib\site-packages (from rio-color) (0.2.2)
Requirement already satisfied: affine in c:\users\ross.winans\appdata\local\continuum\anaconda3\envs\osgeo-36\lib\site-packages (from rasterio>=1.0a11->rio-color) (2.2.1)
Requirement already satisfied: attrs in c:\users\ross.winans\appdata\local\continuum\anaconda3\envs\osgeo-36\lib\site-packages (from rasterio>=1.0a11->rio-color) (18.1.0)
Requirement already satisfied: cligj in c:\users\ross.winans\appdata\local\continuum\anaconda3\envs\osgeo-36\lib\site-packages (from rasterio>=1.0a11->rio-color) (0.4.0)
Requirement already satisfied: numpy in c:\users\ross.winans\appdata\local\continuum\anaconda3\envs\osgeo-36\lib\site-packages (from rasterio>=1.0a11->rio-color) (1.14.3)
Requirement already satisfied: snuggs>=1.4.1 in c:\users\ross.winans\appdata\local\continuum\anaconda3\envs\osgeo-36\lib\site-packages (from rasterio>=1.0a11->rio-color) (1.4.1)
Requirement already satisfied: click-plugins in c:\users\ross.winans\appdata\local\continuum\anaconda3\envs\osgeo-36\lib\site-packages (from rasterio>=1.0a11->rio-color) (1.0.3)
Requirement already satisfied: pyparsing in c:\users\ross.winans\appdata\local\continuum\anaconda3\envs\osgeo-36\lib\site-packages (from snuggs>=1.4.1->rasterio>=1.0a11->rio-color) (2.2.0)
Building wheels for collected packages: rio-color
  Running setup.py bdist_wheel for rio-color ... error
  Complete output from command c:\users\ross.winans\appdata\local\continuum\anaconda3\envs\osgeo-36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ROSS~1.WIN\\AppData\\Local\\Temp\\1\\pip-install-nxcvpadu\\rio-color\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\ROSS~1.WIN\AppData\Local\Temp\1\pip-wheel-evap6m7s --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\rio_color
  copying rio_color\operations.py -> build\lib.win-amd64-3.6\rio_color
  copying rio_color\utils.py -> build\lib.win-amd64-3.6\rio_color
  copying rio_color\workers.py -> build\lib.win-amd64-3.6\rio_color
  copying rio_color\__init__.py -> build\lib.win-amd64-3.6\rio_color
  creating build\lib.win-amd64-3.6\rio_color\scripts
  copying rio_color\scripts\cli.py -> build\lib.win-amd64-3.6\rio_color\scripts
  copying rio_color\scripts\__init__.py -> build\lib.win-amd64-3.6\rio_color\scripts
  running egg_info
  writing rio_color.egg-info\PKG-INFO
  writing dependency_links to rio_color.egg-info\dependency_links.txt
  writing entry points to rio_color.egg-info\entry_points.txt
  writing requirements to rio_color.egg-info\requires.txt
  writing top-level names to rio_color.egg-info\top_level.txt
  reading manifest file 'rio_color.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'rio_color.egg-info\SOURCES.txt'
  copying rio_color\colorspace.c -> build\lib.win-amd64-3.6\rio_color
  copying rio_color\colorspace.pyx -> build\lib.win-amd64-3.6\rio_color
  running build_ext
  building 'rio_color.colorspace' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\rio_color
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\ross.winans\appdata\local\continuum\anaconda3\envs\osgeo-36\lib\site-packages\numpy\core\include -Ic:\users\ross.winans\appdata\local\continuum\anaconda3\envs\osgeo-36\include -Ic:\users\ross.winans\appdata\local\continuum\anaconda3\envs\osgeo-36\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\include" /Tcrio_color/colorspace.c /Fobuild\temp.win-amd64-3.6\Release\rio_color/colorspace.obj -O2
  colorspace.c
  c:\users\ross.winans\appdata\local\continuum\anaconda3\envs\osgeo-36\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.14.26428\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for rio-color
  Running setup.py clean for rio-color
Failed to build rio-color
twisted 17.5.0 has requirement Automat>=0.3.0, but you'll have automat 0.0.0 which is incompatible.
Installing collected packages: rio-color
  Running setup.py install for rio-color ... error
    Complete output from command c:\users\ross.winans\appdata\local\continuum\anaconda3\envs\osgeo-36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ROSS~1.WIN\\AppData\\Local\\Temp\\1\\pip-install-nxcvpadu\\rio-color\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ROSS~1.WIN\AppData\Local\Temp\1\pip-record-h4bnv4_s\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\rio_color
    copying rio_color\operations.py -> build\lib.win-amd64-3.6\rio_color
    copying rio_color\utils.py -> build\lib.win-amd64-3.6\rio_color
    copying rio_color\workers.py -> build\lib.win-amd64-3.6\rio_color
    copying rio_color\__init__.py -> build\lib.win-amd64-3.6\rio_color
    creating build\lib.win-amd64-3.6\rio_color\scripts
    copying rio_color\scripts\cli.py -> build\lib.win-amd64-3.6\rio_color\scripts
    copying rio_color\scripts\__init__.py -> build\lib.win-amd64-3.6\rio_color\scripts
    running egg_info
    writing rio_color.egg-info\PKG-INFO
    writing dependency_links to rio_color.egg-info\dependency_links.txt
    writing entry points to rio_color.egg-info\entry_points.txt
    writing requirements to rio_color.egg-info\requires.txt
    writing top-level names to rio_color.egg-info\top_level.txt
    reading manifest file 'rio_color.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'rio_color.egg-info\SOURCES.txt'
    copying rio_color\colorspace.c -> build\lib.win-amd64-3.6\rio_color
    copying rio_color\colorspace.pyx -> build\lib.win-amd64-3.6\rio_color
    running build_ext
    building 'rio_color.colorspace' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\rio_color
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\ross.winans\appdata\local\continuum\anaconda3\envs\osgeo-36\lib\site-packages\numpy\core\include -Ic:\users\ross.winans\appdata\local\continuum\anaconda3\envs\osgeo-36\include -Ic:\users\ross.winans\appdata\local\continuum\anaconda3\envs\osgeo-36\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\include" /Tcrio_color/colorspace.c /Fobuild\temp.win-amd64-3.6\Release\rio_color/colorspace.obj -O2
    colorspace.c
    c:\users\ross.winans\appdata\local\continuum\anaconda3\envs\osgeo-36\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.14.26428\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\ross.winans\appdata\local\continuum\anaconda3\envs\osgeo-36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ROSS~1.WIN\\AppData\\Local\\Temp\\1\\pip-install-nxcvpadu\\rio-color\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ROSS~1.WIN\AppData\Local\Temp\1\pip-record-h4bnv4_s\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ROSS~1.WIN\AppData\Local\Temp\1\pip-install-nxcvpadu\rio-color\

**Comment by sgillies** [comment]
@rosswin we're not publishing any rio-color binaries for Windows to PyPI. You'll need to wait until there are binaries in conda-forge.

**Comment by curiousnovice** [comment]
@sgillies @rosswin what is the current status of rio-color binaries for Windows.

**Comment by kylebarron** [comment]
Have you tried to install them? You can go to https://pypi.org/project/rio-color/#files and see that there are now wheels for windows
![image](https://user-images.githubusercontent.com/15164633/152407275-91e4a229-a69d-4d17-8fad-8ec94ee42c5d.png)
