### ISSUE TITLE
Releases blocked by lack of wheel building infra

### ISSUE THREAD

**Issue by sgillies** [mapbox/rio-color#65]
Previously, we built wheels on a OS X computer using https://github.com/sgillies/frs-wheel-builds but that project is well out of date. I have no estimate for when we'll be able to make new wheel-building infra for this project.

**Comment by sgillies** [comment]
Here are some pre-release wheels to try: https://pypi.org/project/rio-color/1.0.1.dev0/#files. No manylinux `i686` wheels because there aren't any of those for rasterio. For the same reason, I probably shouldn't have uploaded any pypy or win32 wheels.

@vincentsarago @kylebarron if you get a chance to try these, I'd love to hear how it goes.

**Comment by sgillies** [comment]
I've deleted the cp27*, cp35*, and pp* wheels for this release. No point.

**Comment by kylebarron** [comment]
As mentioned in the PR, I was able to install the Mac 3.7 wheel fine, and importing it worked at least
